# Generated by Django 2.2.1 on 2019-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.URLField(default='', max_length=100, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='文章分类'),
        ),
    ]
